<?php

/**
 * Implements hook_field_formatter_info().
 */
function maxim_filters_field_formatter_info() {
  return array(
    'maxim_video_player' => array(
      'label' => t('Maxim Video Player'),
      'field types' => array('file'),
    ),
    'comma_separated_list' => array(
      'label' => t('Comma Separated List'),
      'field types' => array('taxonomy_term_reference'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function maxim_filters_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $og_element = array();
  $settings = $display['settings'];
  switch ($display['type']) {
    case 'comma_separated_list':
      $term_list = array();
      foreach ($items as $delta => $item) {
        $term_list[] = taxonomy_term_load($item['tid'])->name;
      }
     $element[$delta]['#markup'] = implode(', ', $term_list);
    break;
    case 'maxim_video_player':
      // Common case: each value is displayed individually in a sub-element
      // keyed by delta. The field.tpl.php template specifies the markup
      // wrapping each value.
      foreach ($items as $delta => $item) {
        if(!empty($item['field_media_5min_id']['und']['0']['value'])) {
          //print 5min player script as well as the current node 5min ID value
            $element[$delta]['#markup'] = '<script type="text/javascript" src="http://pshared.5min.com/Scripts/PlayerSeed.js?sid=764&amp;width=620&amp;height=348&amp;shuffle=0&amp;sequential=1&amp;autoStart=true&amp;playList='
              . $item['field_media_5min_id']['und']['0']['value'] . '"></script>';
          $og_element = array(
            '#tag' => 'meta', // The #tag is the html tag - <meta />
            '#attributes' => array( // Set up an array of attributes inside the tag
            'property' => 'og:type', 
            'content' => 'video',
            ),
          );
          drupal_add_html_head($og_element, 'facebook_og_type');
          $og_element = array(
            '#tag' => 'meta', // The #tag is the html tag - <meta />
            '#attributes' => array( // Set up an array of attributes inside the tag
            'property' => 'og:video', 
            'content' => 'http://embed.5min.com/' . $item['field_media_5min_id']['und']['0']['value'] . '/&sid=764&vcdBgColor=%23313131&colorPallet=%23ED1C24&playerActions=696&isAutoStart=true',
            ),
          );
          drupal_add_html_head($og_element, 'facebook_og_video');
          $og_element = array(
            '#tag' => 'meta', // The #tag is the html tag - <meta />
            '#attributes' => array( // Set up an array of attributes inside the tag
            'property' => 'og:video:type', 
            'content' => 'application/x-shockwave-flash',
            ),
          );
          drupal_add_html_head($og_element, 'facebook_og_video_type');
          $og_element = array(
            '#tag' => 'meta', // The #tag is the html tag - <meta />
            '#attributes' => array( // Set up an array of attributes inside the tag
            'property' => 'og:video:width', 
            'content' => '620',
            ),
          );
          drupal_add_html_head($og_element, 'facebook_og_video_width');
          $og_element = array(
            '#tag' => 'meta', // The #tag is the html tag - <meta />
            '#attributes' => array( // Set up an array of attributes inside the tag
            'property' => 'og:video:height', 
            'content' => '348',
            ),
          );
          drupal_add_html_head($og_element, 'facebook_og_video_height');
        }
        elseif (!empty($item['field_media_cdn_url']['und']['0']['value'])) {
        //print the legacy flash player with a direct hardcode to the generic video stub and flv cdn file path
          $element[$delta]['#markup'] = '<object width="620" height="348" id="FiveminPlayer" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000">
            <param name="allowfullscreen" value="true" /><param name="allowScriptAccess" value="always" />
            <param name="movie" value="http://embed.5min.com/399695185/&sid=764&isAutoStart=true" /><param name="flashvars" value="tpvVideoUrl='
            . $item['field_media_cdn_url']['und']['0']['value'] . '" /><param name="wmode" value="window" />
            <embed name="FiveminPlayer" src="http://embed.5min.com/399695185/&sid=764&isAutoStart=true&tpvVideoUrl='
            . $item['field_media_cdn_url']['und']['0']['value'] . '" type="application/x-shockwave-flash" width="620" height="348" allowfullscreen="true" allowScriptAccess="always" wmode="window" ></embed ></object>';
        }
        else {
          $element[$delta]['#markup'] = t('Error: Video Not Found');
        }
      }
      break;
  }
  return $element;
}
