<?php
/**
* hook_form_FORM_ID_alter
*
*/
function todays_girl_filter_override_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "views_exposed_form" && $form['#id'] == "views-exposed-form-channel-girls-todays-girl") {
   
    $form['title_1']['#type'] = "select";
    $form['title_1']['#size'] = null;
    $form['title_1']['#options'] = array(
      'All' => t('<Any>'),
      'a' => t('a'),
      'b' => t('b'),
      'c' => t('c'),
      'd' => t('d'),
      'e' => t('e'),
      'f' => t('f'),
      'g' => t('g'),
      'h' => t('h'),
      'i' => t('i'),
      'j' => t('j'),
      'k' => t('k'),
      'l' => t('l'),
      'm' => t('m'),
      'n' => t('n'),
      'o' => t('o'),
      'p' => t('p'),
      'q' => t('q'),
      'r' => t('r'),
      's' => t('s'),
      't' => t('t'),
      'u' => t('u'),
      'v' => t('v'),
      'w' => t('w'),
      'x' => t('x'),
      'y' => t('y'),
      'z' => t('z'),
    );
    $form['title_1']['#default_value'] = $form['title_1']['#options']['All'];
  }
}
?>
