<?php

/**
* Promotion Bottom floating widget module
*/

/**
* This function places the hidden div tag into a footer block. The JavaScript then performs the actions on this block
*/
function promo_bottom_float_preprocess_page(&$vars) {
  $ad_data = '';
  $ad_link = 'http://www.maxim.com/digital-editions';

  drupal_add_library('system','jquery.cookie');
  $modulepath = 'http://cdn2.maxim.com/maxim/' . drupal_get_path('module', 'promo_bottom_float');

  $ad_data .= <<<EOD
  <div id="promoFloatAd" style="display:none">
    <div class="promoAdTop">
      <a href="{$ad_link}" target="_blank"><img src="{$modulepath}/images/mag_cover_ipad.png" alt="Maxim To Go"/></a>
      <a href="#" class="expandCollapse expanded">Expand/Collapse</a>
      <p><span>Maxim<br />To Go</span></p>
      <a href="#" class="close">Close</a>
    </div>
    <div class="promoAdContent">
      <p>
        <span><img src="{$modulepath}/images/divider.png" /></span>
        Subscribe to Maxim's<br />Digital Editions
      </p>
      <a href="{$ad_link}" target="_blank" class="downloadNowButton">Download Now</a>
      <div class="promoFloatPixel"></div>
    </div>
  </div>
EOD;

  $vars['page']['footer']['promoad'] = array('#markup' => $ad_data);
}
