<?php

/**
* Promotion Bottom floating widget module
*/

/**
* This function places the hidden div tag into a footer block. The JavaScript then performs the actions on this block
*/
function promo_bottom_float_preprocess_page(&$vars) {
  $ad_data = '';
  $ad_link = 'http://www.maxim.com/subscribe/form';

  drupal_add_library('system','jquery.cookie');
  $modulepath = 'http://cdn2.maxim.com/maxim/' . drupal_get_path('module', 'promo_bottom_float');
  //$modulepath = '/' . drupal_get_path('module', 'promo_bottom_float');

  $ad_data .= <<<EOD
  <div id="promoFloatAd" style="display:none">
    <div class="promoAdTop">
      <a href="{$ad_link}" target="_blank"><img src="{$modulepath}/images/max.png" alt="Get your weekly Maxim Newsletter"/></a>
      <a href="#" class="expandCollapse expanded">Expand/Collapse</a>
      <p>Get your weekly<br /><span>Maxim Newsletter</span></p>
      <a href="#" class="close">Close</a>
    </div>
    <div class="promoAdContent">
      <p>
        <a href="{$ad_link}" target="_blank"><img src="{$modulepath}/images/newsletter.png" alt="Get your weekly Maxim Newsletter" /></a>
      </p>
      <div class="downloadNowButton">
      <a href="{$ad_link}" target="_blank"><img src="{$modulepath}/images/btn_newsletter_sign_up.png" /></a>
      </div>
      <div class="promoFloatPixel"></div>
    </div>
  </div>
EOD;

  $vars['page']['footer']['promoad'] = array('#markup' => $ad_data);
}