<?php
// $Id$
require_once ( dirname(__FILE__) . '/bb_hth_settings.inc');
 
function bb_hth_resource_services_resources() {
  return array(
    // STATES LOOKUP
    'states' => array(
      'operations' => array(
        'index' => array(
          'help' => 'retreives list of states',
          'file' => array('name' => 'bb_hth_lookup_resource', 'type' => 'inc', 'module' => 'bb_hth_resource'),
          'callback' => '_bb_hth_lookup_states_retreive',
          'access callback' =>  '_bb_hth_resource_access',
          'access arguments append' => FALSE,
        ),
      ),
    ),
      
    // YEARS LOOKUP
    'years' => array(
      'operations' => array(
        'index' => array(
          'help' => 'retreives list of active hth years',
          'file' => array('name' => 'bb_hth_lookup_resource', 'type' => 'inc', 'module' => 'bb_hth_resource'),
          'callback' => '_bb_hth_lookup_years_retreive',
          'access callback' =>  '_bb_hth_resource_access',
          'access arguments append' => FALSE,
        ),
      ),
    ),
      
    // STANDINGS LOOKUP
    'standings' => array(
      'operations' => array(
        'index' => array(
          'help' => 'retreives list of hth standings',
          'file' => array('name' => 'bb_hth_lookup_resource', 'type' => 'inc', 'module' => 'bb_hth_resource'),
          'callback' => '_bb_hth_lookup_standings_retreive',
          'access callback' =>  '_bb_hth_resource_access',
          'access arguments append' => FALSE,
        ),
      ),
    ),
      
    // HTH BY STATE
    'bb-hth-state' => array(
      'operations' => array(
        'index' => array(
          'help' => 'retrieves profiles by state',
          'file' => array('name' => 'bb_hth_state_resource', 'type' => 'inc', 'module' => 'bb_hth_resource'),
          'callback' => '_bb_hth_state_resource_retreive',
          'access callback' =>  '_bb_hth_resource_access',
          'access arguments append' => TRUE,
          'args' => array(
             array(
              'name' => 'year',
              'type' => 'int',
              'description' => 'hth year',
              'source' => array('path' => '0'),
              'optional' => FALSE,
              'default value' => null,
            ),
            array(
              'name' => 'state',
              'type' => 'string',
              'description' => 'hth state',
              'source' => array('path' => '1'),
              'optional' => TRUE,
              'default value' => null,
            ),
            array(
              'name' => 'state-page',
              'type' => 'int',
              'description' => 'state page number',
              'source' => array('param' => 'statePage'),
              'default value' => '0',
              'optional' => TRUE,
            ),
            array(
              'name' => 'state-ipp',
              'type' => 'int',
              'description' => 'state items per page',
              'source' => array('param' => 'stateIpp'),
              'default value' => '51',
              'optional' => TRUE,
            ),
            array(
              'name' => 'profileCount',
              'type' => 'int',
              'description' => 'number of profiles to Display',
              'source' => array('param' => 'profileCount'),
              'default value' => '4',
              'optional' => TRUE,
            ),
            array(
              'name' => 'status',
              'type' => 'string',
              'description' => 'profiles to return',
              'source' => array('param' => 'status'),
              'optional' => TRUE,
              'default value' => null,
            ),
          ),
        ),
      ),
    ),
      
    // HTH BY STANDING
    'bb-hth-standing' => array(
      'operations' => array(
        'index' => array(
          'help' => 'retrieves profiles by contestant standing',
          'file' => array('name' => 'bb_hth_standing_resource', 'type' => 'inc', 'module' => 'bb_hth_resource'),
          'callback' => '_bb_hth_standing_resource_retreive',
          'access callback' =>  '_bb_hth_resource_access',
          'access arguments append' => TRUE,
          'args' => array(
             array(
              'name' => 'year',
              'type' => 'int',
              'description' => 'hth year',
              'source' => array('path' => '0'),
              'optional' => FALSE,
              'default value' => null,
            ),
            array(
              'name' => 'standing',
              'type' => 'string',
              'description' => 'hth standing',
              'source' => array('path' => '1'),
              'optional' => TRUE,
              'default value' => null,
            ),
            array(
              'name' => 'page',
              'type' => 'int',
              'description' => 'page number',
              'source' => array('param' => 'page'),
              'default value' => '0',
              'optional' => TRUE,
            ),
            array(
              'name' => 'ipp',
              'type' => 'int',
              'description' => 'items per page',
              'source' => array('param' => 'ipp'),
              'default value' => '4',
              'optional' => TRUE,
            ),
          ),
        ),
      ),
    ),      

    // HTH ALL
    'bb-hth-all' => array(
      'operations' => array(
        'index' => array(
          'help' => 'retrieves all profiles',
          'file' => array('name' => 'bb_hth_all_resource', 'type' => 'inc', 'module' => 'bb_hth_resource'),
          'callback' => '_bb_hth_all_resource_retreive',
          'access callback' =>  '_bb_hth_resource_access',
          'access arguments append' => TRUE,
          'args' => array(
             array(
              'name' => 'year',
              'type' => 'int',
              'description' => 'hth year',
              'source' => array('path' => '0'),
              'optional' => FALSE,
              'default value' => null,
            ),
            array(
              'name' => 'page',
              'type' => 'int',
              'description' => 'page number',
              'source' => array('param' => 'page'),
              'default value' => '0',
              'optional' => TRUE,
            ),
            array(
              'name' => 'ipp',
              'type' => 'int',
              'description' => 'items per page',
              'source' => array('param' => 'ipp'),
              'default value' => '4',
              'optional' => TRUE,
            ),
            array(
              'name' => 'status',
              'type' => 'string',
              'description' => 'profiles to return',
              'source' => array('param' => 'status'),
              'optional' => TRUE,
              'default value' => null,
            ),
          ),
        ),
      ),
    ),
      
 // HTH PROFILE
    'bb-hth-profile' => array(
      'operations' => array(
        'retrieve' => array(
          'help' => 'retrieves profile by nid',
          'file' => array('name' => 'bb_hth_profile_resource', 'type' => 'inc', 'module' => 'bb_hth_resource'),
          'callback' => '_bb_hth_profile_resource_retreive',
          'access callback' =>  '_bb_hth_resource_access',
          'access arguments append' => TRUE,
          'args' => array(
            array(
              'name' => 'nid',
              'type' => 'int',
              'description' => 'hth nid',
              'source' => array('path' => '0'),
              'optional' => FALSE,
            ),
            array(
              'name' => 'tab',
              'type' => 'string',
              'description' => 'originating tab',
              'source' => array('path' => '1'),
              'optional' => FALSE,
            ),
          ),
        ),
      ),
    ),
      
    // SEARCH
    'bb-hth' => array(
      'operations' => array(
        'index' => array(
          'help' => 'gets name/state/img/nid of hths',
          'file' => array('file' => 'inc', 'module' => 'bb_hth_resource'),
          'callback' => '_bb_hth_resource_retreive_hth',
          'access callback' =>  '_bb_hth_resource_access',
          'access arguments append' => TRUE,
          'args' => array(
            array(
              'name' => 'year',
              'type' => 'int',
              'description' => 'hth year',
              'source' => array('param' => 'year'),
              'default' => '',
              'optional' => TRUE,
            ),
            array(
              'name' => 'week',
              'type' => 'int',
              'description' => 'hth week',
              'source' => array('param' => 'week'),
              'default' => '',
              'optional' => TRUE,
            ),
            array(
              'name' => 'state',
              'type' => 'string',
              'description' => 'hth state',
              'source' => array('param' => 'state'),
              'default' => '',
              'optional' => TRUE,
            ),
            array(
              'name' => 'standing',
              'type' => 'int',
              'description' => 'hth standing',
              'source' => array('param' => 'status'),
              'default' => '',
              'optional' => TRUE,
            ),
            array(
              'name' => 'page',
              'type' => 'int',
              'description' => 'page number',
              'source' => array('param' => 'page'),
              'default' => '1',
              'optional' => TRUE,
            ),
            array(
              'name' => 'ipp',
              'type' => 'int',
              'description' => 'items per page',
              'source' => array('param' => 'ipp'),
              'default' => '5',
              'optional' => TRUE,
            ),
          ),   
        ),
      ),
    ),
  );
}

function _bb_hth_resource_access() {
  return true;
}