<?php
// $Id$
require_once ( dirname(__FILE__) . '/maxim_data_settings.inc');
require_once ( dirname(__FILE__) . '/maxim_data_common.inc');

function maxim_data_services_resources() {
  return array(
    // JUMBOTRON
    'jumbotron' => array(
      'operations' => array(
        'index' => array(
          'help' => 'retreives maxim jumbotron information',
          'file' => array('name' => 'maxim_data_jumbotron', 'type' => 'inc', 'module' => 'maxim_data'),
          'callback' => '_maxim_data_jumbotron_retreive',
          'access callback' =>  '_maxim_data_services_access',
          'access arguments append' => TRUE,
          'args' => array(
            array(
              'name' => 'cb',
              'type' => 'int',
              'description' => 'cache break',
              'source' => array('param' => 'cb'),
              'default value' => '0',
              'optional' => TRUE,
            ),
            array(
              'name' => 'debug',
              'type' => 'int',
              'description' => 'show debug info',
              'source' => array('param' => 'debug'),
              'default value' => '0',
              'optional' => TRUE,
            ),
          ),
        ),
      ),
    ),
    
    // PROFILE
    'profile' => array(
      'operations' => array(
        'index' => array(
          'help' => 'retreives profile based on nid',
          'file' => array('name' => 'maxim_data_profile', 'type' => 'inc', 'module' => 'maxim_data'),
          'callback' => '_maxim_data_profile_retreive',
          'access callback' =>  '_maxim_data_services_access',
          'access arguments append' => TRUE,
          'args' => array(
            array(
              'name' => 'nid',
              'type' => 'int',
              'description' => 'profile',
              'source' => array('path' => '0'),
              'optional' => FALSE,
            ),
            array(
              'name' => 'cb',
              'type' => 'int',
              'description' => 'cache break',
              'source' => array('param' => 'cb'),
              'default value' => '0',
              'optional' => TRUE,
            ),
            array(
              'name' => 'debug',
              'type' => 'int',
              'description' => 'show debug info',
              'source' => array('param' => 'debug'),
              'default value' => '0',
              'optional' => TRUE,
            ),
          ),
        ),
      ),
    ),
      
    // SLIDESHOW
    'slideshow' => array(
      'operations' => array(
        'index' => array(
          'help' => 'retreives slideshow based on nid',
          'file' => array('name' => 'maxim_data_slideshow', 'type' => 'inc', 'module' => 'maxim_data'),
          'callback' => '_maxim_data_slideshow_retreive',
          'access callback' =>  '_maxim_data_services_access',
          'access arguments append' => TRUE,
          'args' => array(
            array(
              'name' => 'nid',
              'type' => 'int',
              'description' => 'profile',
              'source' => array('path' => '0'),
              'optional' => FALSE,
            ),
            array(
              'name' => 'cb',
              'type' => 'int',
              'description' => 'cache break',
              'source' => array('param' => 'cb'),
              'default value' => '0',
              'optional' => TRUE,
            ),
            array(
              'name' => 'debug',
              'type' => 'int',
              'description' => 'show debug info',
              'source' => array('param' => 'debug'),
              'default value' => '0',
              'optional' => TRUE,
            ),
          ),
        ),
      ),
    ),

    // SLIDESHOW
    'slideshow' => array(
      'operations' => array(
        'index' => array(
          'help' => 'retreives slideshow based on nid',
          'file' => array('name' => 'maxim_data_slideshow', 'type' => 'inc', 'module' => 'maxim_data'),
          'callback' => '_maxim_data_slideshow_retreive',
          'access callback' =>  '_maxim_data_services_access',
          'access arguments append' => TRUE,
          'args' => array(
            array(
              'name' => 'nid',
              'type' => 'int',
              'description' => 'profile',
              'source' => array('path' => '0'),
              'optional' => FALSE,
            ),
            array(
              'name' => 'cb',
              'type' => 'int',
              'description' => 'cache break',
              'source' => array('param' => 'cb'),
              'default value' => '0',
              'optional' => TRUE,
            ),
            array(
              'name' => 'debug',
              'type' => 'int',
              'description' => 'show debug info',
              'source' => array('param' => 'debug'),
              'default value' => '0',
              'optional' => TRUE,
            ),
          ),
        ),
      ),
    ),
      
    // previous_next
    'prev_next' => array(
      'operations' => array(
        'index' => array(
          'help' => 'retreives previous next items',
          'file' => array('name' => 'maxim_data_prev_next', 'type' => 'inc', 'module' => 'maxim_data'),
          'callback' => '_maxim_data_prev_next_retrieve',
          'access callback' =>  '_maxim_data_services_access',
          'access arguments append' => TRUE,
          'args' => array(
            array(
              'name' => 'nid',
              'type' => 'int',
              'description' => 'nid',
              'source' => array('path' => '0'),
              'optional' => FALSE,
            ),
            array(
              'name' => 'wrap',
              'type' => 'int',
              'description' => 'do we wrap around to the beginning/end or do we return null',
              'source' => array('param' => 'page'),
              'default value' => '1',
              'optional' => TRUE,
            ),
            array(
              'name' => 'cb',
              'type' => 'int',
              'description' => 'cache break',
              'source' => array('param' => 'cb'),
              'default value' => '0',
              'optional' => TRUE,
            ),
            array(
              'name' => 'debug',
              'type' => 'int',
              'description' => 'show debug info',
              'source' => array('param' => 'debug'),
              'default value' => '0',
              'optional' => TRUE,
            ),
          ),
        ),
      ),
    ),
      
    // IN THE MAGAZINE
    'in-the-magazine' => array(
      'operations' => array(
        'index' => array(
          'help' => 'retreives items in the magazine',
          'file' => array('name' => 'maxim_data_magazine', 'type' => 'inc', 'module' => 'maxim_data'),
          'callback' => '_maxim_data_magazine_retreive',
          'access callback' =>  '_maxim_data_services_access',
          'access arguments append' => TRUE,
          'args' => array(
            array(
              'name' => 'cb',
              'type' => 'int',
              'description' => 'cache break',
              'source' => array('param' => 'cb'),
              'default value' => '0',
              'optional' => TRUE,
            ),
            array(
              'name' => 'debug',
              'type' => 'int',
              'description' => 'show debug info',
              'source' => array('param' => 'debug'),
              'default value' => '0',
              'optional' => TRUE,
            ),
          ),
        ),
      ),
    ),
  );
}

function _maxim_data_services_access() {
  return true;
}