<?php
// $Id$
require_once ( dirname(__FILE__) . '/maxim_data_settings.inc');
 
function maxim_data_services_resources() {
  return array(
    // JUMBOTRON
    'jumbotron' => array(
      'operations' => array(
        'index' => array(
          'help' => 'retreives maxim jumbotron information',
          'file' => array('name' => 'maxim_data_jumbotron', 'type' => 'inc', 'module' => 'maxim_data'),
          'callback' => '_maxim_data_jumbotron_retreive',
          'access callback' =>  '_maxim_data_services_access',
          'access arguments append' => TRUE,
          'args' => array(
            array(
              'name' => 'cb',
              'type' => 'int',
              'description' => 'cache break',
              'source' => array('param' => 'cb'),
              'default value' => '0',
              'optional' => TRUE,
            ),
          ),
        ),
      ),
    ),
  );
}

function _maxim_data_services_access() {
  return true;
}