<?php
// $Id$

function gamer_girl_voting_resource_services_resources() {
  return array(
   'gamer-girl-vote' => array(
     'retrieve' => array(
       'help' => 'Retrieves vote count for a given gg/nid/day',
       'file' => array('file' => 'inc', 'module' => 'gamer_girl_voting_resource'),
       'callback' => '_gamer_girl_voting_resource_retreive',
       'access callback' =>  '_gamer_girl_voting_resource_access',
       'args' => array(
         array(
           'name' => 'composit_data',
           'type' => 'string',
           'description' => 'The nid of the gg + "~" + uuid',
           'source' => array('path' => '0'),
           'optional' => FALSE,
         ),
       ),
     ),
     'create' => array(
       'help' => 'Creates a vote for a given gg/nid/day',
       'file' => array('file' => 'inc', 'module' => 'gamer_girl_voting_resource'),
       'callback' => '_gamer_girl_voting_resource_create',
       'access callback' => '_gamer_girl_voting_resource_access',
       'args' => array(
         array(
           'name' => 'data',
           'type' => 'array',
           'description' => 'The gg nid/user id',
           'source' => 'data',
           'optional' => FALSE,
         ),
       ),
     ),
   ),
  );
}

function _gamer_girl_voting_resource_access($args) {
  return true;
}

function gamer_girl_voting_resource_block_info() {
  $blocks['gamer_girl_vote_button'] = array(
    'info' => t("This block contains the vote button for a gamer girl profile")
  );

  $blocks['gamer_girl_nav_header'] = array(
    'info' => t("This block contains the gamer girl header image")
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function gamer_girl_voting_resource_block_view($delta = '') {
  $block = array();

  if ($delta == 'gamer_girl_vote_button') {
    $gg_vote  = '<div id="gg_vote">Vote For Me!</div><div id="gg_no_vote_msg" style="display:none"></div>';
    $gg_vote .= '<iframe id="vote_UUID" width="1" height="1" src="about:blank"></iframe>';

    $block['subject'] = t('');
    $block['content'] = array(
      '#markup' => $gg_vote,
      '#title' => t(''),
    );

    $js=<<<JS
     jQuery(document).ready(function() {
       jQuery("#vote_UUID").attr("src","/sites/default/libraries/php/gamer_girl_vote/set_uuid.php?" + Math.floor(Math.random()*1000000000));

       var text = jQuery(".field-name-year-week-competed .field-label").text();
       text = text.replace("Week", "");
       jQuery(".field-name-year-week-competed .field-label").text(text);
     });
JS;

    drupal_add_js($js, array('type' => 'inline', 'scope' => 'header'));
  }
  elseif ($delta == 'gamer_girl_nav_header') {
    $header = '<div class="gamer-girl-header"><a href="/gamergirl/finalists"><img src="http://cdn2.maxim.com/maxim/sites/default/files/profile_header_gamergirl.jpg" /></a></div>';

    $block['subject'] = t('');
    $block['content'] = array(
      '#markup' => $header,
      '#title' => t(''),
    );
  }

  return $block;
}

