<?php

/**
* Promotion Bottom floating widget module
*/

/**
* This function places the hidden div tag into a footer block. The JavaScript then performs the actions on this block
*/
function promo_bottom_float_preprocess_page(&$vars) {
  $ad_data = '';
  $ad_link = 'http://itunes.apple.com/us/app/maxim-magazine/id457038272';

  drupal_add_library('system','jquery.cookie');
  $modulepath = 'http://cdn2.maxim.com/maxim/' . drupal_get_path('module', 'promo_bottom_float');

  $ad_data .= <<<EOD
  <div id="promoFloatAd" style="display:none">
    <div class="promoAdTop">
      <a href="{$ad_link}" target="_blank"><img src="{$modulepath}/images/hotties_ipad.png" alt="Hometown Hotties"/></a>
      <a href="#" class="expandCollapse expanded">Expand/Collapse</a>
      <p>2013's Top 100 <span>Hometown Hotties</span></p>
      <a href="#" class="close">Close</a>
    </div>
    <div class="promoAdContent">
      <p>
        <span><img src="{$modulepath}/images/divider.png" /></span>
        On Sale Now in the Maxim+ App
      </p>
      <a href="{$ad_link}" target="_blank" class="downloadNowButton">Download Now</a>
      <div class="promoFloatPixel"></div>
    </div>
  </div>
EOD;

  $vars['page']['footer']['promoad'] = array('#markup' => $ad_data);
}
