<?php
// $Id$

function _hottie_slotting_resource_create($hth_data) {
  $h = 1;
}



function _hottie_slotting_resource_write_vote($vote_data) {
  $vote = array();
  $criteria = array();

  /*
  $vote['entity_type'] = 'node';
  $vote['value_type'] = 'points';
  $vote['entity_id'] = $vote_data['nid'];
  $vote['value'] = 1;
  $vote['uid'] = $vote_data['uid'];
  $vote['tag'] = $vote_data['vote-campaign-data']['voting_api_tag'];

  $votingapi_set_votes = votingapi_set_votes($vote, $criteria);

  if (is_array($votingapi_set_votes)) {
    return ('vote_entered');
  }
  else {
    return ('error_adding_vote');
  }
   */
}
