<?php

/**
 * @file
 * Install, update and uninstall functions for the maxim_core module.
 */

/**
 * Enable the Node References, Page Manager and Views modules.
 */
function maxim_core_update_7000() {
 $module_list = array('node_reference','page_manager', 'views');

 module_enable($module_list);
}

/**
 * Enable the Panels module.
 */
function maxim_core_update_7001() {
 $module_list = array('panels');

 module_enable($module_list);
}

