<?php
/**
 * @file
 * Code for the Maxim Core feature.
 */

include_once('maxim_core.features.inc');

function maxim_core_menu() {
  $items['slideshow/%node'] = array(
    'title' => 'Slideshow',
    'page callback' => 'slideshow_json',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );
  
  return $items;
}

function slideshow_json($node) {
  $slides = array();
  foreach ($node->field_slides as $key => $field) {
    $slides[] = field_view_field('node', $node, 'field_slides', $field);
  }
  drupal_json_output($slides);
}

/**
 * Implementation of hook_preprocess_node().
 *
 * Add slideshow slides as JSON to Drupal.settings.
 */
function maxim_core_preprocess_node(&$variables) {
  if ('slideshow' == $variables['node']->type) {
    foreach ($variables['node']->field_slides as $key => $field) {
      $slides[] = render(field_view_field('node', $variables['node'], 'field_slides', $field));
    }
    dsm(drupal_json_encode($slides));
    drupal_add_js(array('slides' => $slides), 'setting');
  }
}

/**
 * Implementation of hook_preprocess_panels_pane().
 */
function maxim_core_preprocess_panels_pane(&$variables) {
  if ('partner_links' == $variables['pane']->subtype) {
    $term = taxonomy_term_load($variables['title']);
    $partner_logo = field_view_value('taxonomy_term', $term, 'field_partner_image', $term->field_partner_image[LANGUAGE_NONE][0]);
    $partner_logo['#image_style'] = 'thumbnail';
    $variables['title'] = drupal_render($partner_logo);
    $variables['classes_array'][] = 'partner-feed-' . str_replace(' ', '-', strtolower($term->name));
  }
}
