<?php

/**
 * Implements hook_field_formatter_info().
 */
function maxim_video_field_formatter_info() {
  return array(
    'maxim_video_player' => array(
      'label' => t('Maxim Video Player'),
      'field types' => array('file'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function maxim_video_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $settings = $display['settings'];
  switch ($display['type']) {
    case 'maxim_video_player':
      // Common case: each value is displayed individually in a sub-element
      // keyed by delta. The field.tpl.php template specifies the markup
      // wrapping each value.
      foreach ($items as $delta => $item) {
        if(!empty($item['field_media_5min_id']['und']['0']['value'])) {
        //print 5min player script as well as the current node 5min ID value
          $element[$delta]['#markup'] = '<script type="text/javascript" src="http://pshared.5min.com/Scripts/PlayerSeed.js?sid=764&amp;amp;width=620&amp;amp;height=348&amp;amp;shuffle=0&amp;amp;sequential=1&amp;amp;autoStart=false&amp;amp;playList='
            . $item['field_media_5min_id']['und']['0']['value'] . '"></script>';
        }
        elseif (!empty($item['field_media_cdn_url']['und']['0']['value'])) {
        //print the legacy flash player with a direct hardcode to the generic video stub and flv cdn file path
          $element[$delta]['#markup'] = '<object width="620" height="348" id="FiveminPlayer" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000">
            <param name="allowfullscreen" value="true" /><param name="allowScriptAccess" value="always" />
            <param name="movie" value="http://embed.5min.com/399695185/&sid=764&isAutoStart=true" /><param name="flashvars" value="tpvVideoUrl='
            . $item['field_media_cdn_url']['und']['0']['value'] . '" /><param name="wmode" value="window" />
            <embed name="FiveminPlayer" src="http://embed.5min.com/399695185/&sid=764&isAutoStart=true&tpvVideoUrl='
            . $item['field_media_cdn_url']['und']['0']['value'] . '" type="application/x-shockwave-flash" width="620" height="348" allowfullscreen="true" allowScriptAccess="always" wmode="window" ></embed ></object>';
        }
        else {
          $element[$delta]['#markup'] = t('Error: Video Not Found');
        }
      }
      break;
  }
  return $element;
}


// function maxim_base_alpha_preprocess_node_video(&$node) {
//   if (!empty($node['field_media_file']['und']['0']['field_media_5min_id']['und']['0']['value'])) {
//      //print 5min player script as well as the current node 5min ID value
//      $videocode = '<script type="text/javascript" src="http://pshared.5min.com/Scripts/PlayerSeed.js?sid=764&amp;amp;width=620&amp;amp;height=348&amp;amp;shuffle=0&amp;amp;sequential=1&amp;amp;autoStart=false&amp;amp;playList=' . $node['field_media_file']['und']['0']['field_media_5min_id']['und']['0']['value'] . '"></script>';
//    }
//    else if (!empty($node['field_media_file']['und']['0']['field_media_cdn_url']['und']['0']['value'])){
//      //print the legacy flash player with a direct hardcode to the generic video stub and flv cdn file path
//      $videocode = '<object width="620" height="348" id="FiveminPlayer" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"><param name="allowfullscreen" value="true" /><param name="allowScriptAccess" value="always" /><param name="movie" value="http://embed.5min.com/399695185/&sid=764&isAutoStart=true" /><param name="flashvars" value="tpvVideoUrl=' . $node['field_media_file']['und']['0']['field_media_cdn_url']['und']['0']['value'] . '" /><param name="wmode" value="window" /><embed name="FiveminPlayer" src="http://embed.5min.com/399695185/&sid=764&isAutoStart=true&tpvVideoUrl=' . $node['field_media_file']['und']['0']['field_media_cdn_url']['und']['0']['value'] . '" type="application/x-shockwave-flash" width="620" height="348" allowfullscreen="true" allowScriptAccess="always" wmode="window" ></embed ></object>';
//    }
//    else {
//      $videocode = t('Error: Video Not Found');
//    }
//
//    $page_title = '<h1 class="title" id="page-title">Maxim TV</h1>';
//    $title = "<h2 class=\"node-title\"><a href=\"{$node['node_url']}\" title=\"{$node['title']}\">{$node['title']}</a></h2>";
//    $node['content']['body']['0']['#prefix'] = $page_title . $videocode . $title;
//    $node['title'] = null;
// }