<?php
// $Id$

function hth_voting_resource_services_resources() {
  return array(
    'create-uid' => array(
      'operations' => array(
        'index' => array(
          'help' => 'generates a maxim uid',
          'file' => array('name' => 'hth_uid_resource', 'type' => 'inc', 'module' => 'hth_voting_resource'),
          'callback' => '_generate_uid',
          'access callback' =>  '_hth_voting_resource_access',
        )
      ),
    ),

    'voting-status' => array(
      'operations' => array(
        'index' => array(
          'help' => 'retrieves voting info for a given nid/day/uid combo',
          'file' => array('name' => 'hth_voting_resource', 'type' => 'inc', 'module' => 'hth_voting_resource'),
          'callback' => '_hth_voting_resource_retreive',
          'access callback' =>  '_hth_voting_resource_access',
          'access arguments append' => TRUE,
          'args' => array(
            array(
              'name' => 'nid',
              'type' => 'int',
              'description' => 'The nid of the hth',
              'source' => array('path' => '0'),
              'optional' => FALSE,
            ),
            array(
              'name' => 'uid',
              'type' => 'int',
              'description' => 'the uid of the requester',
              'source' => array('path' => '1'),
              'optional' => FALSE,
            ),
            array(
             'name' => 'campaign',
             'type' => 'int',
             'description' => 'the hth campaign',
             'source' => array('param' => '0'),
             'optional' => TRUE,
             'default value' => 'hth',
            ),
          ),
        ),
      ),
    ),

    'enter-vote' => array(
      'operations' => array(
        'create' => array(
          'help' => 'Creates a vote for a given hth/nid/day',
          'file' => array('name' => 'hth_voting_resource', 'type' => 'inc', 'module' => 'hth_voting_resource'),
          'callback' => '_hth_voting_resource_create',
          'access callback' => '_hth_voting_resource_access',
          'args' => array(
            array(
              'name' => 'data',
              'type' => 'array',
              'description' => 'The hth nid/user id/campaign',
              'source' => 'data',
              'optional' => FALSE,
            ),
          ),
        ),
      ),
    ),
  );
}

function _hth_voting_resource_access($args) {
  return true;
}

function hth_voting_resource_block_info() {
  $blocks['hth_nav_header'] = array(
    'info' => t("Generic Hometown Hotties Header")
  );

  $blocks['hth_nav_header_2014'] = array(
    'info' => t("2014 Hometown Hotties Header")
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function hth_voting_resource_block_view($delta = '') {
  $block = array();

  if (strpos($delta, 'hth_nav_header') !== FALSE) {
    $contest_week = variable_get('hth_contest_week', 0);
    $contest_year = variable_get('hth_contest_year', 0);
    $voting_open = 1;

    $weeks = '';
    if ($contest_week == 1) {
      $weeks = '<li id="hottie-head-1"><a href="/hometown-hotties/'. $contest_year .'/week1">1</a></li><li id="hottie-head-2" class="future-week">2</li><li id="hottie-head-3" class="future-week">3</li><li id="hottie-head-4" class="future-week">4</li><li id="hottie-head-5" class="future-week">5</li><li id="hottie-head-semi-finals" class="future-week">Semis</li><li id="hottie-head-finals" class="future-week">Finals</li>';
    }
    elseif ($contest_week == 2) {
      $weeks = '<li id="hottie-head-1""><a href="/hometown-hotties/'. $contest_year .'/week1">1</a></li><li id="hottie-head-2"><a href="/hometown-hotties/'. $contest_year .'/week2">2</a></li><li id="hottie-head-3" class="future-week">3</li><li id="hottie-head-4" class="future-week">4</li><li id="hottie-head-5" class="future-week">5</li><li id="hottie-head-semi-finals" class="future-week">Semis</li><li id="hottie-head-finals" class="future-week">Finals</li>';
    }
    elseif ($contest_week == 3) {
      $weeks = '<li id="hottie-head-1"><a href="/hometown-hotties/'. $contest_year .'/week1">1</a></li><li id="hottie-head-2"><a href="/hometown-hotties/'. $contest_year .'/week2">2</a></li><li id="hottie-head-3"><a href="/hometown-hotties/'. $contest_year .'/week3">3</a></li><li id="hottie-head-4" class="future-week">4</li><li id="hottie-head-5" class="future-week">5</li><li id="hottie-head-semi-finals" class="future-week">Semis</li><li id="hottie-head-finals" class="future-week">Finals</li>';
    }
    elseif ($contest_week == 4) {
      $weeks = '<li id="hottie-head-1"><a href="/hometown-hotties/'. $contest_year .'/week1">1</a></li><li id="hottie-head-2"><a href="/hometown-hotties/'. $contest_year .'/week2">2</a></li><li id="hottie-head-3"><a href="/hometown-hotties/'. $contest_year .'/week3">3</a></li><li id="hottie-head-4"><a href="/hometown-hotties/'. $contest_year .'/week4">4</a></li><li id="hottie-head-5" class="future-week">5</li><li id="hottie-head-semi-finals" class="future-week">Semis</li><li id="hottie-head-finals" class="future-week">Finals</li>';
    }
    elseif ($contest_week == 5) {
      $weeks = '<li id="hottie-head-1"><a href="/hometown-hotties/'. $contest_year .'/week1">1</a></li><li id="hottie-head-2"><a href="/hometown-hotties/'. $contest_year .'/week2">2</a></li><li id="hottie-head-3"><a href="/hometown-hotties/'. $contest_year .'/week3">3</a></li><li id="hottie-head-4"><a href="/hometown-hotties/'. $contest_year .'/week4">4</a></li><li id="hottie-head-5"><a href="/hometown-hotties/'. $contest_year .'/week5">5</a></li><li id="hottie-head-semi-finals" class="future-week">Semis</li><li id="hottie-head-finals" class="future-week">Finals</li>';
    }
    elseif ($contest_week == 'semi_finals') {
      $weeks = '<li id="hottie-head-1"><a href="/hometown-hotties/'. $contest_year .'/week1">1</a></li><li id="hottie-head-2"><a href="/hometown-hotties/'. $contest_year .'/week2">2</a></li><li id="hottie-head-3"><a href="/hometown-hotties/'. $contest_year .'/week3">3</a></li><li id="hottie-head-4"><a href="/hometown-hotties/'. $contest_year .'/week4">4</a></li><li id="hottie-head-5"><a href="/hometown-hotties/'. $contest_year .'/week5">5</a><li id="hottie-head-semi-finals"><a href="/hometown-hotties/'. $contest_year .'/semi-finals">Semis</a></li><li id="hottie-head-finals" class="future-week">Finals</li>';
    }
    elseif ($contest_week == 'finals') {
      $weeks = '<li id="hottie-head-1"><a href="/hometown-hotties/'. $contest_year .'/week1">1</a></li><li id="hottie-head-2"><a href="/hometown-hotties/'. $contest_year .'/week2">2</a></li><li id="hottie-head-3"><a href="/hometown-hotties/'. $contest_year .'/week3">3</a></li><li id="hottie-head-4"><a href="/hometown-hotties/'. $contest_year .'/week4">4</a></li><li id="hottie-head-5"><a href="/hometown-hotties/'. $contest_year .'/week5">5</a><li id="hottie-head-semi-finals"><a href="/hometown-hotties/'. $contest_year .'/semi-finals">Semis</a></li><li id="hottie-head-finals"><a href="/hometown-hotties/'. $contest_year .'/finals">Finals</a></li>';
    } else {
      $voting_open = 0;
      $weeks = '<li id="hottie-head-1"><a href="/hometown-hotties/'. $contest_year .'/week1">1</a></li><li id="hottie-head-2"><a href="/hometown-hotties/'. $contest_year .'/week2">2</a></li><li id="hottie-head-3"><a href="/hometown-hotties/'. $contest_year .'/week3">3</a></li><li id="hottie-head-4"><a href="/hometown-hotties/'. $contest_year .'/week4">4</a></li><li id="hottie-head-5"><a href="/hometown-hotties/'. $contest_year .'/week5">5</a></li><li id="hottie-head-semi-finals" class="future-week">Semis</li><li id="hottie-head-finals" class="future-week">a href="/hometown-hotties/'. $contest_year .'/finals">Finals<a></li>';
    }

    switch($delta) {
      case 'hth_nav_header_2014':
        $header_txt = '<div id="hth_header_container"><div class="hottie-header"><a href="/hometown-hotties/2014"><img src="http://cdn2.maxim.com/maxim/sites/default/files/hotties/hth_2014_header.jpg" /></a></div>';
      break;
      default:
        $header_txt = '<div id="hth_header_container"><div class="hottie-header"><a href="/girls/hometown-hotties"><img src="http://cdn2.maxim.com/maxim/sites/default/files/hotties/hth_2013_header2.png" /></a></div>';
      break;
    }

    if (strlen($weeks) > 0) {
      if ($voting_open == 1) {
        $vote_title = 'VOTING WEEK:';
      } else {
        $vote_title = 'WEEK:';
      }
      $header_txt .= '<ul id="hth_header"><li class="first-element"><a href="/hometown-hotties-entry-form-2014">ENTRY FORM</a> | ' . $vote_title . '</li>'.$weeks.'</ul>';
    }
    $header_txt .= '</div><div style="clear: both"></div> ';

    $block['subject'] = t('');
    $block['content'] = array(
      '#markup' => $header_txt,
      '#title' => t(''),
    );

    $js=<<<JS
      jQuery(function(){
        if (typeof Drupal.settings.Maxim.hottie.hottie_year !== "undefined" && typeof Drupal.settings.Maxim.hottie.hottie_week !== "undefined") {
          if (Drupal.settings.Maxim.hottie.hottie_year == {$contest_year}) {
            jQuery("#hth_header").show();
            if (Drupal.settings.Maxim.hottie.hottie_week == 'finals' || Drupal.settings.Maxim.hottie.hottie_week == 'semi-finals') {
              jQuery("#hottie-head-" + Drupal.settings.Maxim.hottie.hottie_week).addClass('finals-selected');
            }
            else {
              jQuery("#hottie-head-" + Drupal.settings.Maxim.hottie.hottie_week).addClass('hth_h_selweek');
            }
          }
        }
      });
JS;

    drupal_add_js($js, array('type' => 'inline', 'scope' => 'header'));
  }

  return $block;
}

function hth_voting_resource_votingapi_metadata_alter(&$data) {
  $data['tags']['vote_semi_finals'] = array(
    'name' => t('HTH Semi-Finals'),
    'description' => t('HTH Semi-Finals'),
  );
  $data['tags']['vote_finals'] = array(
    'name' => t('HTH Finals'),
    'description' => t('HTH Finals'),
  );
  $data['tags']['hth_vote_2014'] = array(
    'name' => t('2014 HTH Voting'),
    'description' => t('2014 HTH Voting'),
  );
}
