<?php
// $Id$

function hth_voting_resource_js_init() {
  drupal_add_css(drupal_get_path('module', 'hth_voting_resource_js') . '/css/hth_voting.css');
  drupal_add_js(drupal_get_path('module', 'hth_voting_resource_js') . '/js/hth_voting.js');
}

function hth_voting_resource_js_default_services_endpoint() {
  $endpoints = array();

  $endpoint = new stdClass;
  $endpoint->disabled = FALSE; /* Edit this to true to make a default endpoint disabled initially */
  $endpoint->name = 'hth_voting_js';
  $endpoint->title = 'HTH Vote API';
  $endpoint->server = 'rest_server';
  $endpoint->path = 'js-api';
  $endpoint->authentication = array();
  $endpoint->resources = array(
    'vote' => array(
      'alias' => '',
      'operations' => array(
        'create' => array(
          'enabled' => 1,
        ),
        'retrieve' => array(
          'enabled' => 1,
        ),
      ),
    ),
  );
  $endpoints[] = $endpoint;

  return $endpoints;
}