<?php
/**
 * @file
 * A simple wrapper for the Sailthru API Client
 * https://github.com/sailthru/sailthru-php5-client
 */

function sailthru_client_block_info() {
  $blocks['sailthru_client'] = array(
    'info' => t('Sailthru API'),
  );
  return $blocks;
}

/**
 * Implementation of hook_menu().
 */
function sailthru_client_menu() {
  $items['admin/config/sailthru-client'] = array(
    'title' => 'Sailthru Settings',
    'description' => 'Configure your Sailthru account',
    'position' => 'right',
    'weight' => -5,
    'page callback' => 'system_admin_menu_block_page',
    //'page arguments' => array('sailthru_client_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'sailthru_client.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/sailthru-client/settings'] = array(
    'title' => 'Manage Sailthru settings',
    'description' => 'Configure your Sailthru account.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sailthru_client_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'sailthru_client.admin.inc',
  );

  return $items;
}

/*
 * Constructor for Sailthru client
 */
function sailthru_client_get_client() {
  $api_key = variable_get('sailthru_client_api_key', '');
  $api_secret = variable_get('sailthru_client_api_secret', '');
  $api_uri = variable_get('sailthru_client_api_uri', 'http://api.sailthru.com');
  if (empty($api_key)) {
    watchdog('sailthru', t('The Sailthru API Key has not been configured. Please visit the configuration page.') . ' ' . l('Configure Sailthru Module', '/admin/config/sailthru-client/settings'));
    drupal_set_message(t('Unable to connect to Sailthru, please check your settings'), 'error', false);
    return false;
  }
  if (empty($api_secret)) {
    watchdog('sailthru', t('The Sailthru API Secret has not been configured. Please visit the configuration page.') . ' ' . l('Configure Sailthru Module', '/admin/config/sailthru-client/settings'));
    drupal_set_message(t('Unable to connect to Sailthru, please check your settings'), 'error', false);
    return false;
  }
  if (empty($api_uri)) {
    watchdog('sailthru', t('The Sailthru URI has not been configured. Please visit the configuration page.') . ' ' . l('Configure Sailthru Module', '/admin/config/sailthru-client/settings'));
    drupal_set_message(t('Unable to connect to Sailthru, please check your settings'), 'error', false);
    return false;
  }

  require_once('lib/sailthru/Sailthru_Util.php');
  require_once('lib/sailthru/Sailthru_Client_Exception.php');
  require_once('lib/sailthru/Sailthru_Client.php');

  return new Sailthru_Client($api_key, $api_secret, $api_uri);
}
